name: py38
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - configargparse=1.4
  - matplotlib=3.7.1
  - numpy=1.24.3
  - pandas=1.5.3
  - pillow=9.4.0
  - python=3.8.17
  - pytorch=2.0.1
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - tensorboardx=2.2
  - torchvision=0.15.2
  - tqdm
  - yaml
  - pip:
      - einops
      - imageio
      - scikit-image
